package database

// governanceAutomationSchemaStatements installs the pre-production baseline
// for reports, bans, site-affairs content, the seed crawler and project update
// jobs. PostgreSQL is the durable source of truth for every workflow.
func governanceAutomationSchemaStatements() []string {
	return []string{
		`create table reports (
			id bigserial primary key,
			public_id text not null unique default new_public_id() check(public_id ~ '^[a-z0-9]{9}$'),
			target_type text not null,
			target_public_id text not null,
			target_author_id bigint references users(id) on delete set null,
			reporter_id bigint not null references users(id) on delete cascade,
			reason_code text not null,
			reason_version integer not null default 1 check(reason_version>0),
			reason_text_snapshot text not null,
			custom_reason text not null default '',
			detail text not null default '',
			status text not null default 'pending',
			claimed_by bigint references users(id) on delete set null,
			claimed_at timestamptz,
			lock_version bigint not null default 1,
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now(),
			resolved_at timestamptz,
			check(target_type in ('mod','plugin','map','shader','resource_pack','datapack','addon','discussion','bug','news','tutorial','skin','blueprint','server','comment','user')),
			check(status in ('pending','in_review','resolved_valid','resolved_invalid','cancelled')),
			check(reason_code<>'other' or btrim(custom_reason)<>'')
		)`,
		`create unique index uq_reports_open_reporter_target on reports(reporter_id,target_type,target_public_id)
			where status in ('pending','in_review')`,
		`create index idx_reports_queue on reports(status,created_at,id)`,
		`create index idx_reports_target_history on reports(target_type,target_public_id,created_at desc,id desc)`,
		`create table report_snapshots (
			report_id bigint primary key references reports(id) on delete cascade,
			schema_version integer not null default 1 check(schema_version>0),
			payload jsonb not null,
			content_sha256 text not null check(content_sha256 ~ '^[a-f0-9]{64}$'),
			created_at timestamptz not null default now()
		)`,
		`create table report_evidence (
			id bigserial primary key,
			public_id text not null unique default new_public_id() check(public_id ~ '^[a-z0-9]{9}$'),
			uploader_id bigint not null references users(id) on delete cascade,
			report_id bigint references reports(id) on delete set null,
			object_key text not null unique,
			original_name text not null,
			content_type text not null,
			byte_size bigint not null check(byte_size>0),
			sha256 text not null check(sha256 ~ '^[a-f0-9]{64}$'),
			scan_status text not null default 'pending',
			status text not null default 'temporary',
			created_at timestamptz not null default now(),
			cleanup_after timestamptz not null default now()+interval '24 hours',
			deleted_at timestamptz,
			delete_attempts integer not null default 0,
			last_error text not null default '',
			check(scan_status in ('pending','clean','rejected','failed')),
			check(status in ('temporary','bound','pending_delete','deleted'))
		)`,
		`create index idx_report_evidence_cleanup on report_evidence(status,cleanup_after,id)
			where status in ('temporary','pending_delete')`,
		`create index idx_report_evidence_report on report_evidence(report_id,id)`,
		`create table report_reviews (
			id bigserial primary key,
			report_id bigint not null references reports(id) on delete cascade,
			reviewer_id bigint not null references users(id) on delete restrict,
			conclusion text not null,
			note text not null default '',
			idempotency_key text not null,
			created_at timestamptz not null default now(),
			unique(report_id,idempotency_key),
			check(conclusion in ('valid','invalid','reopened'))
		)`,
		`create table moderation_actions (
			id bigserial primary key,
			public_id text not null unique default new_public_id() check(public_id ~ '^[a-z0-9]{9}$'),
			report_id bigint references reports(id) on delete set null,
			action_type text not null,
			target_type text not null,
			target_public_id text not null,
			actor_id bigint not null references users(id) on delete restrict,
			target_user_id bigint references users(id) on delete set null,
			before_summary jsonb not null default '{}'::jsonb,
			after_summary jsonb not null default '{}'::jsonb,
			reason text not null default '',
			idempotency_key text not null,
			created_at timestamptz not null default now(),
			unique(action_type,target_type,target_public_id,idempotency_key)
		)`,
		`create table ban_reasons (
			code text primary key,
			translations jsonb not null default '{}'::jsonb,
			active boolean not null default true,
			sort_order integer not null default 0
		)`,
		`create table ban_records (
			id bigserial primary key,
			public_id text not null unique default new_public_id() check(public_id ~ '^[a-z0-9]{9}$'),
			user_id bigint not null references users(id) on delete restrict,
			moderator_id bigint not null references users(id) on delete restrict,
			report_id bigint references reports(id) on delete set null,
			reason_code text not null references ban_reasons(code),
			custom_reason text not null default '',
			public_record_markdown text not null default '',
			internal_note text not null default '',
			username_snapshot text not null,
			avatar_snapshot text not null default '',
			status text not null default 'active',
			starts_at timestamptz not null default now(),
			ends_at timestamptz,
			revoked_at timestamptz,
			revoked_by bigint references users(id) on delete set null,
			revoke_reason text not null default '',
			created_at timestamptz not null default now(),
			check(status in ('active','revoked','expired')),
			check(reason_code<>'other' or btrim(custom_reason)<>'')
		)`,
		`create unique index uq_ban_records_active_user on ban_records(user_id)
			where status='active'`,
		`create index idx_ban_records_public on ban_records(created_at desc,id desc)`,
		`create table site_pages (
			id bigserial primary key,
			code text not null unique,
			status text not null default 'draft',
			published_revision bigint not null default 0,
			updated_by bigint references users(id) on delete set null,
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now(),
			check(status in ('draft','published'))
		)`,
		`create table site_page_translations (
			page_id bigint not null references site_pages(id) on delete cascade,
			locale text not null,
			title text not null,
			body_markdown text not null,
			status text not null default 'draft',
			revision bigint not null default 1,
			updated_by bigint references users(id) on delete set null,
			updated_at timestamptz not null default now(),
			primary key(page_id,locale),
			check(status in ('draft','published'))
		)`,
		`create table site_changelogs (
			id bigserial primary key,
			public_id text not null unique default new_public_id() check(public_id ~ '^[a-z0-9]{9}$'),
			change_date date not null,
			status text not null default 'draft',
			created_by bigint references users(id) on delete set null,
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now(),
			check(status in ('draft','published'))
		)`,
		`create index idx_site_changelogs_public on site_changelogs(change_date desc,id desc) where status='published'`,
		`create table site_changelog_translations (
			changelog_id bigint not null references site_changelogs(id) on delete cascade,
			locale text not null,
			title text not null,
			body_markdown text not null,
			updated_by bigint references users(id) on delete set null,
			updated_at timestamptz not null default now(),
			primary key(changelog_id,locale)
		)`,
		`create table seed_crawler_configs (
			id boolean primary key default true check(id),
			enabled boolean not null default false,
			project_types text[] not null default array['mod','plugin','shader_pack','resource_pack'],
			batch_size integer not null default 1 check(batch_size between 1 and 50),
			daily_limit integer not null default 20 check(daily_limit between 1 and 1000),
			minimum_downloads bigint not null default 100 check(minimum_downloads>=0),
			interval_seconds integer not null default 21600 check(interval_seconds>=60),
			max_concurrency integer not null default 1 check(max_concurrency between 1 and 16),
			ai_daily_token_budget bigint not null default 200000 check(ai_daily_token_budget>=0),
			auto_submit_review boolean not null default false,
			last_run_at timestamptz,
			next_run_at timestamptz,
			updated_by bigint references users(id) on delete set null,
			updated_at timestamptz not null default now()
		)`,
		`create table seed_crawler_runs (
			id bigserial primary key,
			public_id text not null unique default new_public_id() check(public_id ~ '^[a-z0-9]{9}$'),
			status text not null default 'pending',
			dry_run boolean not null default false,
			requested_by bigint references users(id) on delete set null,
			lease_owner text not null default '',
			lease_expires_at timestamptz,
			attempts integer not null default 0,
			next_attempt_at timestamptz not null default now(),
			stats jsonb not null default '{}'::jsonb,
			last_error text not null default '',
			created_at timestamptz not null default now(),
			started_at timestamptz,
			finished_at timestamptz,
			check(status in ('pending','running','completed','failed','paused'))
		)`,
		`create index idx_seed_crawler_runs_ready on seed_crawler_runs(status,next_attempt_at,id)`,
		`create table seed_crawler_candidates (
			id bigserial primary key,
			run_id bigint references seed_crawler_runs(id) on delete set null,
			external_project_id text not null,
			project_type text not null,
			downloads bigint not null default 0,
			status text not null default 'candidate',
			payload jsonb not null default '{}'::jsonb,
			last_error text not null default '',
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now(),
			unique(external_project_id),
			check(project_type in ('mod','plugin','shader_pack','resource_pack'))
		)`,
		`create table seed_crawler_translation_tasks (
			candidate_id bigint not null references seed_crawler_candidates(id) on delete cascade,
			locale text not null,
			status text not null default 'pending',
			attempts integer not null default 0,
			input_tokens bigint not null default 0,
			output_tokens bigint not null default 0,
			last_error text not null default '',
			updated_at timestamptz not null default now(),
			primary key(candidate_id,locale),
			check(status in ('pending','running','completed','failed'))
		)`,
		`create table project_external_sources (
			id bigserial primary key,
			project_route_id bigint not null references public_routes(id) on delete cascade,
			source_type text not null,
			external_project_id text not null,
			external_project_url text not null,
			verified_at timestamptz not null,
			verified_by bigint references users(id) on delete set null,
			created_at timestamptz not null default now(),
			unique(project_route_id,source_type),
			unique(source_type,external_project_id),
			check(source_type in ('modrinth','curseforge','github'))
		)`,
		`create table license_policies (
			spdx_id text primary key,
			redistribution_allowed boolean not null,
			notes text not null default '',
			updated_by bigint references users(id) on delete set null,
			updated_at timestamptz not null default now()
		)`,
		`create table project_auto_update_settings (
			id bigserial primary key,
			project_route_id bigint not null references public_routes(id) on delete cascade,
			update_kind text not null,
			source_type text,
			interval_code text not null,
			enabled boolean not null default false,
			next_run_at timestamptz,
			last_run_at timestamptz,
			last_status text not null default 'never',
			last_error_code text not null default '',
			last_error text not null default '',
			configured_by bigint references users(id) on delete set null,
			license_override boolean not null default false,
			license_override_reason text not null default '',
			license_override_source text not null default '',
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now(),
			unique(project_route_id,update_kind),
			check(update_kind in ('minecraft_versions','changelog','site_downloads')),
			check(interval_code in ('week','month','quarter','half_year','year','never')),
			check(source_type is null or source_type in ('modrinth','curseforge','github')),
			check(update_kind<>'minecraft_versions' or source_type is distinct from 'github')
		)`,
		`create index idx_project_auto_update_due on project_auto_update_settings(next_run_at,id)
			where enabled and next_run_at is not null`,
		`create table project_auto_update_runs (
			id bigserial primary key,
			public_id text not null unique default new_public_id() check(public_id ~ '^[a-z0-9]{9}$'),
			setting_id bigint not null references project_auto_update_settings(id) on delete cascade,
			status text not null default 'pending',
			lease_owner text not null default '',
			lease_expires_at timestamptz,
			attempts integer not null default 0,
			next_attempt_at timestamptz not null default now(),
			result jsonb not null default '{}'::jsonb,
			last_error_code text not null default '',
			last_error text not null default '',
			created_at timestamptz not null default now(),
			started_at timestamptz,
			finished_at timestamptz,
			check(status in ('pending','running','completed','failed','dead_letter'))
		)`,
		`create unique index uq_project_auto_update_active_run on project_auto_update_runs(setting_id)
			where status in ('pending','running')`,
		`create index idx_project_auto_update_runs_ready on project_auto_update_runs(status,next_attempt_at,id)`,
		`create table external_release_bindings (
			id bigserial primary key,
			project_route_id bigint not null references public_routes(id) on delete cascade,
			source_type text not null,
			external_release_id text not null,
			changelog_public_id text,
			source_managed boolean not null default true,
			manual_override boolean not null default false,
			external_body_hash text not null default '',
			external_url text not null default '',
			metadata jsonb not null default '{}'::jsonb,
			created_at timestamptz not null default now(),
			updated_at timestamptz not null default now(),
			unique(source_type,external_release_id)
		)`,
		`create table mirrored_project_files (
			id bigserial primary key,
			project_route_id bigint not null references public_routes(id) on delete cascade,
			source_type text not null,
			external_file_id text not null,
			file_sha256 text not null,
			byte_size bigint not null check(byte_size>0),
			oss_file_id bigint references oss_files(id) on delete set null,
			license_spdx_id text,
			metadata jsonb not null default '{}'::jsonb,
			status text not null default 'pending',
			created_at timestamptz not null default now(),
			unique(source_type,external_file_id),
			unique(source_type,file_sha256,byte_size),
			check(status in ('pending','scanning','ready','review','failed','source_changed'))
		)`,
	}
}
