package httpapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"strings"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"mcmods-cn-backend/internal/config"
	"mcmods-cn-backend/internal/security"
)

type favoriteScaleCollectionPage struct {
	Items []struct {
		ID string `json:"id"`
	} `json:"items"`
	Limit      int    `json:"limit"`
	HasMore    bool   `json:"hasMore"`
	NextCursor string `json:"nextCursor"`
}

type favoriteScaleItemPage struct {
	Items []struct {
		EntityPublicID string `json:"entityPublicId"`
	} `json:"items"`
	Limit      int    `json:"limit"`
	HasMore    bool   `json:"hasMore"`
	NextCursor string `json:"nextCursor"`
}

func TestFavoriteHandlersBoundMillionRowsAndAvoidCollectionFanoutIntegration(t *testing.T) {
	if os.Getenv("MCMODS_RUN_DB_INTEGRATION") != "1" {
		t.Skip("set MCMODS_RUN_DB_INTEGRATION=1 to verify favorite pagination")
	}
	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
	t.Cleanup(cancel)
	poolConfig, err := pgxpool.ParseConfig(config.Load().DB.ConnString())
	if err != nil {
		t.Fatal(err)
	}
	counter := &integrationQueryCounter{}
	poolConfig.MaxConns = 1
	poolConfig.MinConns = 1
	poolConfig.ConnConfig.Tracer = counter
	pool, err := pgxpool.NewWithConfig(ctx, poolConfig)
	if err != nil {
		t.Fatal(err)
	}
	t.Cleanup(pool.Close)

	base := time.Date(2025, 1, 1, 0, 0, 0, 0, time.UTC)
	if _, err = pool.Exec(ctx, `create temporary table favorite_collections(
		id bigint generated by default as identity(start with 2000000) primary key,
		public_id text not null default 'd00000000',user_id bigint not null,name text not null,
		is_default boolean not null default false,is_public boolean not null default false,
		created_at timestamptz not null default now(),updated_at timestamptz not null default now());
	create unique index favorite_collections_one_default on favorite_collections(user_id) where is_default;
	create unique index favorite_collections_public_id on favorite_collections(public_id);
	create index idx_favorite_collections_user_page
		on favorite_collections(user_id,is_default desc,created_at,id);
	create temporary table favorite_collection_items(
		id bigint primary key,collection_id bigint not null,entity_type text not null,
		entity_id bigint not null,created_at timestamptz not null);
	create index idx_favorite_items_collection_page
		on favorite_collection_items(collection_id,created_at desc,id desc);
	create index idx_favorite_items_target_collection
		on favorite_collection_items(entity_type,entity_id,collection_id);
	create unique index favorite_items_unique_target
		on favorite_collection_items(collection_id,entity_type,entity_id);
	create temporary table public_routes(
		id bigint primary key,entity_type text not null,public_id text not null,
		internal_id bigint not null,canonical_path text not null);
	create unique index public_routes_target on public_routes(entity_type,internal_id);
	create unique index public_routes_public_id on public_routes(public_id);
	create temporary table mods(
		id bigint primary key,primary_name text not null,secondary_name text not null default '',
		icon_url text not null default '',slug text not null,review_status text not null,
		submitted_by bigint not null,updated_at timestamptz not null);
	create temporary table modpacks(
		id bigint primary key,primary_name text not null,secondary_name text not null default '',
		icon_url text not null default '',slug text not null,review_status text not null,
		submitted_by bigint not null,updated_at timestamptz not null);
	create temporary table blueprints(
		id bigint primary key,public_id text not null,title text not null,cover_object_key text not null default '',
		status text not null,review_status text not null,owner_id bigint not null,updated_at timestamptz not null);
	create temporary table system_settings(key text primary key,value jsonb not null)`); err != nil {
		t.Fatal(err)
	}
	if _, err = pool.Exec(ctx, `insert into favorite_collections(
		id,public_id,user_id,name,is_default,is_public,created_at)
		select value,'c'||lpad(value::text,8,'0'),42,'collection '||value,value=1,true,
			$1::timestamptz+value*interval '1 microsecond'
		from generate_series(1,1000000) value`, base); err != nil {
		t.Fatal(err)
	}
	if _, err = pool.Exec(ctx, `insert into public_routes
		select value,'mod','m'||lpad(value::text,8,'0'),value,'/mods/m'||lpad(value::text,8,'0')
		from generate_series(1,1000000) value`); err != nil {
		t.Fatal(err)
	}
	if _, err = pool.Exec(ctx, `insert into mods(id,primary_name,slug,review_status,submitted_by,updated_at)
		select value,'mod '||value,'mod-'||value,'approved',42,$1::timestamptz
		from generate_series(1,1000000) value`, base); err != nil {
		t.Fatal(err)
	}
	if _, err = pool.Exec(ctx, `insert into favorite_collection_items
		select value,2,'mod',value,$1::timestamptz+value*interval '1 microsecond'
		from generate_series(1,1000000) value`, base); err != nil {
		t.Fatal(err)
	}
	if _, err = pool.Exec(ctx, `analyze favorite_collections; analyze favorite_collection_items;
		analyze public_routes; analyze mods`); err != nil {
		t.Fatal(err)
	}

	server := &Server{db: pool}
	claims := security.Claims{Subject: 42}
	loadCollections := func(cursor string) favoriteScaleCollectionPage {
		t.Helper()
		path := "/api/v1/users/me/favorite-collections?limit=20"
		if cursor != "" {
			path += "&cursor=" + url.QueryEscape(cursor)
		}
		counter.queries.Store(0)
		request := httptest.NewRequest(http.MethodGet, path, nil)
		request = request.WithContext(context.WithValue(ctx, claimsContextKey, claims))
		response := httptest.NewRecorder()
		server.favoriteCollections(response, request)
		if response.Code != http.StatusOK {
			t.Fatalf("collection status=%d body=%s", response.Code, response.Body.String())
		}
		if queries := counter.queries.Load(); queries != 2 {
			t.Fatalf("favorite collection queries=%d want=2 (default=1,page=1)", queries)
		}
		if response.Body.Len() > 64<<10 {
			t.Fatalf("favorite collection page is unexpectedly large: %d bytes", response.Body.Len())
		}
		var envelope struct {
			Data favoriteScaleCollectionPage `json:"data"`
		}
		if err = json.Unmarshal(response.Body.Bytes(), &envelope); err != nil {
			t.Fatal(err)
		}
		return envelope.Data
	}

	firstCollections := loadCollections("")
	assertFavoriteScalePage(t, len(firstCollections.Items), firstCollections.Limit, firstCollections.HasMore, firstCollections.NextCursor)
	if _, err = pool.Exec(ctx, `insert into favorite_collections(
		id,public_id,user_id,name,is_public,created_at) values(1000001,'c01000001',42,'concurrent',true,$1)`,
		base.Add(10*time.Microsecond)); err != nil {
		t.Fatal(err)
	}
	secondCollections := loadCollections(firstCollections.NextCursor)
	assertFavoriteScalePage(t, len(secondCollections.Items), secondCollections.Limit, secondCollections.HasMore, secondCollections.NextCursor)
	collectionIDs := make(map[string]struct{}, len(firstCollections.Items))
	for _, item := range firstCollections.Items {
		collectionIDs[item.ID] = struct{}{}
	}
	for _, item := range secondCollections.Items {
		if item.ID == "c01000001" {
			t.Fatal("concurrently inserted earlier collection drifted into an anchored later page")
		}
		if _, duplicate := collectionIDs[item.ID]; duplicate {
			t.Fatalf("duplicate collection across pages: %s", item.ID)
		}
	}

	loadItems := func(cursor string) favoriteScaleItemPage {
		t.Helper()
		path := "/api/v1/users/me/favorite-collections/c00000002/items?limit=20"
		if cursor != "" {
			path += "&cursor=" + url.QueryEscape(cursor)
		}
		counter.queries.Store(0)
		request := httptest.NewRequest(http.MethodGet, path, nil)
		request.SetPathValue("id", "c00000002")
		request = request.WithContext(context.WithValue(ctx, claimsContextKey, claims))
		response := httptest.NewRecorder()
		server.favoriteCollectionItems(response, request)
		if response.Code != http.StatusOK {
			t.Fatalf("item status=%d body=%s", response.Code, response.Body.String())
		}
		if queries := counter.queries.Load(); queries != 2 {
			t.Fatalf("favorite item queries=%d want=2 (page=1,settings=1)", queries)
		}
		if response.Body.Len() > 128<<10 {
			t.Fatalf("favorite item page is unexpectedly large: %d bytes", response.Body.Len())
		}
		var envelope struct {
			Data favoriteScaleItemPage `json:"data"`
		}
		if err = json.Unmarshal(response.Body.Bytes(), &envelope); err != nil {
			t.Fatal(err)
		}
		return envelope.Data
	}

	firstItems := loadItems("")
	assertFavoriteScalePage(t, len(firstItems.Items), firstItems.Limit, firstItems.HasMore, firstItems.NextCursor)
	if _, err = pool.Exec(ctx, `insert into public_routes values(1000001,'mod','m01000001',1000001,'/mods/m01000001')`); err != nil {
		t.Fatal(err)
	}
	if _, err = pool.Exec(ctx, `insert into mods(id,primary_name,slug,review_status,submitted_by,updated_at)
		values(1000001,'concurrent mod','concurrent-mod','approved',42,$1)`, base.Add(2*time.Second)); err != nil {
		t.Fatal(err)
	}
	if _, err = pool.Exec(ctx, `insert into favorite_collection_items values(1000001,2,'mod',1000001,$1)`, base.Add(2*time.Second)); err != nil {
		t.Fatal(err)
	}
	secondItems := loadItems(firstItems.NextCursor)
	assertFavoriteScalePage(t, len(secondItems.Items), secondItems.Limit, secondItems.HasMore, secondItems.NextCursor)
	itemIDs := make(map[string]struct{}, len(firstItems.Items))
	for _, item := range firstItems.Items {
		itemIDs[item.EntityPublicID] = struct{}{}
	}
	for _, item := range secondItems.Items {
		if item.EntityPublicID == "m01000001" {
			t.Fatal("concurrently inserted newer favorite drifted into an anchored later page")
		}
		if _, duplicate := itemIDs[item.EntityPublicID]; duplicate {
			t.Fatalf("duplicate favorite target across pages: %s", item.EntityPublicID)
		}
	}

	publicIDs := make([]string, 100)
	for index := range publicIDs {
		publicIDs[index] = fmt.Sprintf("m%08d", index+1)
	}
	body, err := json.Marshal(map[string]any{"entityType": "mod", "entityPublicIds": publicIDs})
	if err != nil {
		t.Fatal(err)
	}
	counter.queries.Store(0)
	request := httptest.NewRequest(http.MethodPost, "/api/v1/users/me/favorites/summary", bytes.NewReader(body))
	request = request.WithContext(context.WithValue(ctx, claimsContextKey, claims))
	response := httptest.NewRecorder()
	server.favoriteMembershipSummary(response, request)
	if response.Code != http.StatusOK {
		t.Fatalf("summary status=%d body=%s", response.Code, response.Body.String())
	}
	if queries := counter.queries.Load(); queries != 1 {
		t.Fatalf("favorite membership summary queries=%d want=1", queries)
	}
	var summaryEnvelope struct {
		Data struct {
			EntityPublicIDs []string `json:"entityPublicIds"`
		} `json:"data"`
	}
	if err = json.Unmarshal(response.Body.Bytes(), &summaryEnvelope); err != nil {
		t.Fatal(err)
	}
	if len(summaryEnvelope.Data.EntityPublicIDs) != 100 || response.Body.Len() > 16<<10 {
		t.Fatalf("summary targets=%d bytes=%d", len(summaryEnvelope.Data.EntityPublicIDs), response.Body.Len())
	}

	collectionRequest, err := parseFavoriteCollectionPageRequest(url.Values{"limit": {"100"}}, 42, true, claims)
	if err != nil {
		t.Fatal(err)
	}
	collectionRequest.Cursor = &favoriteCollectionPageCursor{
		Version: favoritePageCursorVersion, Scope: collectionRequest.Scope, IsDefault: false,
		CreatedAt: base.Add(500000 * time.Microsecond), ID: 500000,
	}
	collectionQuery, collectionArguments := favoriteCollectionPageSQL(collectionRequest)
	collectionPlan, collectionWall := adminProjectScalePlan(t, ctx, pool, collectionQuery, collectionArguments...)
	assertFavoriteScalePlan(t, collectionPlan, "idx_favorite_collections_user_page", "favorite_collections", collectionWall)

	itemRequest, err := parseFavoriteItemPageRequest(url.Values{"limit": {"100"}}, 42, true, "c00000002", claims)
	if err != nil {
		t.Fatal(err)
	}
	itemRequest.Cursor = &favoriteItemPageCursor{
		Version: favoritePageCursorVersion, Scope: itemRequest.Scope,
		CreatedAt: base.Add(500000 * time.Microsecond), ID: 500000,
	}
	itemQuery, itemArguments := favoriteItemPageSQL(itemRequest)
	itemPlan, itemWall := adminProjectScalePlan(t, ctx, pool, itemQuery, itemArguments...)
	assertFavoriteScalePlan(t, itemPlan, "idx_favorite_items_collection_page", "favorite_collection_items", itemWall)

	summaryRequest, err := normalizeFavoriteMembershipSummaryRequest(favoriteMembershipSummaryRequest{
		EntityType: "mod", EntityPublicIDs: publicIDs,
	})
	if err != nil {
		t.Fatal(err)
	}
	summaryQuery, summaryArguments := favoriteMembershipSummarySQL(summaryRequest, 42, false)
	summaryPlan, summaryWall := adminProjectScalePlan(t, ctx, pool, summaryQuery, summaryArguments...)
	assertFavoriteSummaryScalePlan(t, summaryPlan, summaryWall)
	t.Logf("PERF051 million-row handlers: collections=2 queries, items=2 queries, summary=1 query; deep plans=%s/%s/%s",
		collectionWall, itemWall, summaryWall)
}

func assertFavoriteScalePage(t *testing.T, items, limit int, hasMore bool, nextCursor string) {
	t.Helper()
	if items != 20 || limit != 20 || !hasMore || nextCursor == "" {
		t.Fatalf("favorite page items=%d limit=%d hasMore=%v cursor=%q", items, limit, hasMore, nextCursor)
	}
}

func assertFavoriteScalePlan(t *testing.T, plan, index, table string, wall time.Duration) {
	t.Helper()
	if !strings.Contains(plan, index) || strings.Contains(plan, "seq scan on "+table) ||
		strings.Contains(plan, "sort  (") || wall > 2*time.Second {
		t.Fatalf("PERF051 deep page lost bounded %s access in %s:\n%s", index, wall, plan)
	}
}

func assertFavoriteSummaryScalePlan(t *testing.T, plan string, wall time.Duration) {
	t.Helper()
	if !strings.Contains(plan, "idx_favorite_items_target_collection") ||
		strings.Contains(plan, "seq scan on favorite_collection_items") || wall > 2*time.Second {
		t.Fatalf("PERF051 membership summary lost bounded target lookup in %s:\n%s", wall, plan)
	}
}
